# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape, random_tensor.dtype

(tensor([[0.0802, 0.3091, 0.7574, 0.1099, 0.6173, 0.5973, 0.4945],
         [0.1313, 0.3235, 0.7284, 0.7298, 0.4755, 0.6673, 0.2959],
         [0.3205, 0.7708, 0.1049, 0.7038, 0.8805, 0.2617, 0.3670],
         [0.4544, 0.8120, 0.4422, 0.8229, 0.2081, 0.7675, 0.0932],
         [0.3552, 0.3476, 0.5740, 0.1625, 0.2911, 0.5121, 0.9839],
         [0.8981, 0.1961, 0.1488, 0.1261, 0.8320, 0.1717, 0.1986],
         [0.9588, 0.4028, 0.8915, 0.8094, 0.8262, 0.1436, 0.3763]]),
 torch.Size([7, 7]),
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
tensor_A = torch.rand(1, 7)
tensor_B = tensor_A.T  # or tensor_A.reshape(7, 1)
print(tensor_A)
print(tensor_B)

# Perform matrix multiplication
matmul_AB = tensor_A.matmul(tensor_B)
print(matmul_AB, matmul_AB.shape)

# Squeeze tensor
squeezed_tensor = matmul_AB.squeeze()
print(squeezed_tensor, squeezed_tensor.shape)
print(squeezed_tensor.unsqueeze(0), squeezed_tensor.unsqueeze(0).shape)

tensor([[0.6949, 0.4485, 0.2135, 0.3818, 0.1539, 0.1051, 0.7030]])
tensor([[0.6949],
        [0.4485],
        [0.2135],
        [0.3818],
        [0.1539],
        [0.1051],
        [0.7030]])
tensor([[1.4043]]) torch.Size([1, 1])
tensor(1.4043) torch.Size([])
tensor([1.4043]) torch.Size([1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [25]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)

# Create two random tensors
tensor_C = torch.rand(7, 7)
print(tensor_C, tensor_C.shape)

tensor_D = torch.rand(7, 1)
print(tensor_D, tensor_D.shape)

# Matrix multiply tensors
matmul_CD = tensor_C.matmul(tensor_D)
print(matmul_CD, matmul_CD.shape)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) torch.Size([7, 7])
tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]]) torch.Size([7, 1])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
